---
title: Zašto pad cijene Bitcoina nije iznenađenje?
author: Mislav Sagovac
date: '2018-11-27'
slug: za-to-pad-cijene-bitcoina-nije-iznena-enje
categories:
  - Ekonomika
tags:
  - Bitcoin
subtitle: ''
---

Bitcoin je u posljednjih nekoliko tjedana [izgubio](https://www.coinbase.com/price/bitcoin) veliki dio vrijednosti. Cijena je pala s otprilike 6.500\$ na 3.700\$, što je pad od otprilike 40%. Međutim ovakva kretanja su samo dio duljeg trenda pada cijene Bitcoina (u prosincu 2017 cijena je dosegla 19.500$). U ovom postu objašnjavam zašto se ovakav pad mogao predvidjeti i zašto možemo očekivati daljnji pad cijene Bitcoina. Post je orijentiran na ekonomski aspekt analize, odnosno na pregled kritike Bitcoina kao kriptovalute iznesenih od strane brojnih poznatih ekonomista. U postu se dakle pruža pregled kritika koje su iznesene u blogovima ili znanstvenim istraživanjima. Kritike su prvenstveno usmjerene na Bitcoin kao najpoznatiju kriptovalutu, ali slične kritike vrijede i za ostale poznate kriptovalute.

Prvo, ne postoji dodana vrijednost u korištenju Bitcoina kao sredstva plaćanja u odnosu na uobičajena plaćanja kreditnim i debitnim karticama. Ova kritika iznesena je u više postova ([Krugman](https://www.nytimes.com/2018/01/29/opinion/bitcoin-bubble-fraud.html?partner=rss&emc=rss), [Money Banking]( https://www.moneyandbanking.com/commentary/2017/12/3/bitcoin-and-fundamentals), [Douglass Cambel](https://douglaslcampbell.blogspot.com/2017/11/an-economists-take-on-bitcoin-and.html)). Ako se usporedi s plaćanjem PayPal-om, Venmo-om i ostalim poznatim plaćanjima temeljenim na kreditnim i debitnim karticama, Bitcoin ne pruža nikakvu prednost. Dapače, Bitcoin je uglavnom skuplji i sporiji način plaćanja (zanimljivo je da čak i [konferencije](https://www.businessinsider.com/bitcoin-conference-stops-accepting-bitcoin-network-fees-congestion-2018-1) o Bitcoinu ne prihvaća plaćanje Bitcoinom). Jedina funkcija koju Bitcoin u tom smislu može ispuniti, pored klasičnih sredstva plaćanja, je anonimnost. Nitko ne može pratiti trag Bitcoina, pa je on postao vrlo koristan instrument financiranja nelegalnih aktivnosti i izbjegavanja postojećih regulacija. Primjerice, na blogu [Money Banking]( https://www.moneyandbanking.com/commentary/2017/12/3/bitcoin-and-fundamentals)., autori su pokazali da je u 2016. godini gotovo 97% transakcija Bitcoinom bilo locirano u Kini. To je bilo razdoblje snažnih kapitalnih kontrola, posebno kontrole odljeva kapitala uslijed nestabilnosti na financijskim tržištima. Gotovo sve transakcije Bitcoinom bile su usmjerene na izvlačenje novaca iz Kine uslijed zabrane transfera novca iz zemlje. Nakon reakcije Kineske vlade u pokušaja [kontroliranja]( https://www.coindesk.com/chinas-central-bank-continue-bitcoin-exchange-inspections) transakcija Bitcoinom, broj transakcija u Kini se značajno smanjio. Dakle, postoji granica tolerancije nelegalnih transakcija od strane centralnih vlasti, čak i kada je u pitanju Bitcoin. Sve to upućuje na osnovnu tezu – Bitcoin se uglavnom koristi za nelegalne aktivnosti: kupoprodaja oružja, pranje novca, trgovanje ljudima, izbjegavanje plaćanja poreza i slično. 

Druga kritika odnosi se na troškove održavanja sustava. „Poizvodnja“ Bitcoina je vrlo skupa. Prema podacima sa web stranice [Digiconomist](https://digiconomist.net/bitcoin-energy-consumption), procijenjena godišnja potrošnja električne energije za održavanje Bitcoin sustava iznosi 53 TWh. Riječ je o količini energije dovoljnoj za opskrbu 4.9 milijuna kućanstava u SAD-u. Prema podacima s iste stranice, energija koja se potroši na održavanje Bitcoina mogla bi opskrbiti cijelu državu Bangladeš. Ako se gleda u postotku od ukupno potrošene energije, Bitcoin čini 0.24% ukupno potrošene električne energije u cijelom svijetu, što je otprilike tri puta više od potrošene električne energije svih transakcija VISA-om. Zbog svega navedenog, [neki]( https://newmonetarism.blogspot.com/2018/01/is-bitcoin-waste-of-resources.html) održavanje Bitcoina smatraju beskorisnim „rasipanjem resursa“.

Valja napomenuti da kriptovalute nisu valute u izvornom smislu riječi. Kriptovalute ne ispunjavaju jednu osnovnu funkciju valuta (novca): nisu mjerilo vrijednosti.  Oni su ustvari digitalni ekvivalent za dolar ili euro. Dodatno, Bitcoin se ni u jednoj državi nije nametnuo kao ključno sredstvo plaćanja, a kapitalni dobici se tretiraju kao oporezivi dohodak, što je vrlo neobično svojstvo za imovinu koja se smatra novcem. Dodatno, Bitcoin karakterizira izrazita volatilnost pa je posljedično svako ulaganje u Bitcoin izrazito špekulativno. Ovu kritiku navodi većina postova i radova koji pišu o Bitcoinu (pogledati primjerice [post]( https://andolfatto.blogspot.com/2013/04/why-gold-and-bitcoin-make-lousy-money.html) Davida Andolfatta). Kada bi Bitcoin bila valuta, posljednjih godina bismo prolazili kroz nevjerojatne inflacijske i deflacijske epizode, koje bi zasigurno narušile stabilnost monetarnog sustava. Zamislite na primjer da kupite automobil preko web trgovine za 10 Bitcoina. Drugi dan, u trenutku plaćanja cijena Bitcoina naraste za 10%. Osjećaj frustracije koji bi osjetio kupac u tom trenutku bila bi nepodnošljiva. Zbog odsustva ovih temeljnih funkcija novca, neki [istraživači]( https://econospeak.blogspot.com/2017/12/is-bitcoin-speculative-bubble.html) smatraju da Bitcoin nema nikakvu fundamentalnu vrijednost.

Bitcoin se temelji na pukom povjerenju. Često se to puko povjerenje (načelo fiat novca) uspoređuje klasičnim fiat novcem poput dolara. Međutim, prihvaćanje nacionalnih valuta od strane država i centralnih vlasti  daje klasičnim fiat valutama značajku stabilnosti. Primjerice, Bitcoin je od trenutka kada je dosegnuo najvišu vrijednost izgubio  oko 50% vrijednosti. Kada bi Bitcoin bio stvarna valuta to bi podrazumijevalo inflaciju u iznosu od oko 10.000%. Stephen Wiliamson jasno [pokazuje]( https://newmonetarism.blogspot.com/2018/01/is-bitcoin-waste-of-resources.html) razliku između Bitcoina, zlata i tradicionalnih valuta. Dva ključna obilježja koja imaju klasične valute, a nema Bitcoin su 1) elastičnost ponude 2) stabilnost cijena (za detalje pogledati post).

U kritici Bitcoina nikako se ne smije zaobići sigurnost. Bitcoin je podložan cjenovnim manipulacijama i [prevarama](https://www.ccn.com/biggest-theft-history-know-far-530-million-coincheck-hack/). Primjerice [grupa autora](https://voxeu.org/article/price-manipulation-bitcoin-ecosystem) je pokazala da je u 2013. godini samo jedan trgovac (Mt. Gox) svojim trgovanjem uspio podići cijenu Bitcoina s okvirnih 150\$ na 1000\$. Kada je isti trgovac propao 2014. godine, Bitcoin je započeo slobodni pad sve do 2016. godine. Rast cijena Bitcoina bio je pod snažnim utjecajem (da ne kažemo kontrolom) jednog trgovca.

Rast cijene Bitcoina može se gledati i s psihološke perspektive (bihevioralne ekonomike). Jedan od najvećih stručnjaka za bihevioralne financije, Rober Schiller, još je 2014 [tvrdio]( https://www.nytimes.com/2014/03/02/business/in-search-of-a-stable-electronic-currency.html) da je Bitcoin očiti primjer financijskog mjehura. Rast cijena Bitcoina bio je očiti primjer manije za držanjem imovine samo radi očekivanja pada cijene (bez ikakvih fundamentalnih kriterija). Rast cijena je pojačan novinskim člancima o Bitcoinu čiji je narativ često sadržavao riječi poput „nova era“ ili „revolucija novca“. Schiller je više puta ponavljao da Bitcoin ima sve karakteristike mjehura (npr. [ovjde](https://www.cnbc.com/2018/05/30/bitcoin-could-be-extinct-by-2118-yales-robert-shiller.html) i [ovdje](https://www.cnbc.com/2018/04/13/the-bitcoin-bubble-is-an-example-of-faddish-human-behavior-shiller.html)).

Sve ove kritike iznesene od strane ekonomista u posljednjih nekoliko godina mogli su biti dobar indikator kretanja očekivane cijene Bitcoina u budućnosti. Većina ekonomista se slagala da je Bitcoin bubble koji će se ispuhati. To se i dogodilo.

Preostala je još jedna nepoznanica oko Bitcoina, koja bi mogla imati veliki utjecaj na cijenu u budućnosti. S obzirom da se nalazimo u najdužem bikovom tržištu u modernoj povijesti, sasvim je izvjesno da nas uskoro čeka recesija i razdoblje medvjeđeg tržišta. Hoće li to biti prekid fiskalne ekspanzije u SAD-u, kriza u Kini ili nešto treće nije toliko bitno. Sigurno je da globalni dohodak imati nekoliko mjeseci korekcije. Nepoznanica je kako će se Bitcoin ponašati u vrijeme recesije. Većina imovine u vrijeme recesije gubi na vrijednosti (dionice, nekretnine), ali postoji imovina za kojom potražnja raste nakon pojave recesije (najbolji primjer su dolar i zlato) . U tom smislu, postavlja se pitanje kako će se investitori odnositi prema Bitcoinu, kao digitalnom zlatu  ili prenapuhanom mjehuru? Mislim da je drugo izglednije. Teško je zamisliti da investitori sigurnu luku traže u imovini koja je visoko volatilna, a čija je buduća vrijednost izrazito neizvjesna. Dodatno, zlati nema supstituta među plemenitim metalima, dok Bitcoin ima mnoštvo supstituta što ga čini manje izglednim izborom za sigurnu imovinu. Ako je potonje točno, Bitcoin može dosegnuti niske razine nakon pojave recesije, možda i 500$. Neki tvrde da je to nemoguće zbog ograničene ponude Bitcoina i očekivane konstantne ponude kada se izrudare svi Bitcoini. Međutim, ništa ne garantira rast potražnje ili čak održavanje potražnje za Bitcoinima. S druge strane, potražnja za klasičnim valutama je na neki način osigurana jer svaka država očekuje plaćanje poreza u jednoj od valuta, pa se može očekivati i održavanje ili najčešće rast potražnje za novcem. 

Na kraju treba reći da ovaj post ne opovrgava moguću korist u upotrebi blockchain tehnologije. Dapače, može se očekivati da financijske institucije, pa čak i [vlade]( http://andolfatto.blogspot.com/2015/02/fedcoin-on-desirability-of-government.html) i [centralne banke]( https://voxeu.org/article/competition-between-government-money-and-cryptocurrencies) počinju koristiti blockchain tehnologiju. Međutim, to je tema za poseban post.
