---
title: Digitalna ekonomija  u Hrvatskoj
author: Luka Šikić
date: '2018-12-03'
slug: digitalna-ekonomija-u-hrvatskoj
categories:
  - Ekonomika
  - Firme
tags: 
  - Digitalna ekonomija
subtitle: ''
---
Digitalne tehnologije omogućavaju smanjenje troškova pohrane, obrade i prijenosa podataka i zbog toga imaju snažan transformacijski utjecaj na mikro- i makro- ekonomske trendove i strukturu.  Obzirom da strukturu troškova u digitalnoj ekonomiji karakterizira [pad čitavog niza standardnih troškova](https://www.nber.org/papers/w23684) sa kojima se suočavaju tradicionalni sektori, poslovne inicijative za poduzeća iz digitalne ekonomije naglašeno idu u smjeru razvoja tehnologije u širem smislu kao krajnjeg proizvoda. Takva tehnološka intenzivnost bi se očekivano trebala odraziti u povećanju ukupnih tehnoloških kapaciteta i produktivnosti gospodarstva. Zainteresiranost nositelja politika za poticaj digitalnoj ekonomiji kao i njihova očekivanja, vidljivi su na svim razinama.  Pogledajmo stoga kako stoji hrvatski digitalni sektor u komparativnoj perspektivi.

U nastojanju boljeg razumijevanja trendova u digitalnoj ekonomiji EU je pokrenula projekt stvaranja jedinstvenog europskog digitalnog tržišta 2015. godine.  Prema EU, riječ je o tržištu koje je procijenjeno na 415 mlrd EUR godišnje, a poduzeća iz tog sektora  imaju snažan uzjecaj na kreiranje novih radnih mjesta te su značajan generator povećanja produktivnosti ekonomije. EU platforma za analizu digitalne ekonomije se zasniva na [Digital Economy and Society Index (DESI)](https://digital-agenda-data.eu/charts/desi-composite#chart={%22indicator%22:%22DESI_SLIDERS%22,%22breakdown%22:{%22DESI_1_CONN%22:5,%22DESI_2_HC%22:5,%22DESI_3_UI%22:5,%22DESI_4_IDT%22:5,%22DESI_5_DPS%22:5},%22unit-measure%22:%22pc_DESI_SLIDERS%22,%22time-period%22:%222018%22}). DESI je kompozitni indeks koji se sastoji od 5 dimenzija: povezivost (i.e. infrastruktura), ljudskog kapitala i digitalnih vještina, utilizacije internetskih servisa među građanstvom, integracija digitalne tehnologije u poslovanju te digitalnih javnih usluga. Pri tome svaka dimenzija sadrži čitav niz [sub-kategorija](https://digital-agenda-data.eu/charts/analyse-one-indicator-and-compare-countries#chart={%22indicator-group%22:%22research-and-development%22,%22indicator%22:%22H2020_EC_funding%22,%22breakdown%22:%22orgclass_total%22,%22unit-measure%22:%22euro_x_million_of_GDP%22,%22ref-area%22:[%22BE%22,%22BG%22,%22CZ%22,%22DK%22,%22DE%22,%22EE%22,%22IE%22,%22EL%22,%22ES%22,%22FR%22,%22IT%22,%22CY%22,%22LV%22,%22LT%22,%22LU%22,%22HU%22,%22MT%22,%22NL%22,%22AT%22,%22PL%22,%22PT%22,%22RO%22,%22SI%22,%22SK%22,%22FI%22,%22SE%22,%22UK%22,%22EU27%22,%22EU%22,%22EU28%22,%22HR%22,%22IS%22,%22NO%22]} ) koje omogućuju detaljniji uvid u specifične aspekte i strukturu šireg procesa digitalne transformacije.

Hrvatska  spada u skupinu manje uspješnih DESI zemalja te se u 2018. nalazi na 22  mjestu od 28 EU zemalja. Iako je relativna pozicija Hrvatske u odnosu na EU prosjek prema DESI indeksu relativno loša, trend kretanja je pozitivan te je pozicija u odnosu na prethodnu godinu poboljšana. Moguće je reći da postoji konvergencija Hrvatske prema EU prosjeku od početka mjerenja indeksa 2014. godine. Ukoliko se promotri struktura DESI komponenti za  Hrvatsku, vidljivo je da se hrvatski građani koriste internetom znatno više od EU prosjeka (rang 11)  pa je to jedina sastavnica indeksa u odnosu na ostale 4 koja je viša od EU prosjeka. Na području ljudskog kapitala i IT vještina su  također ostvareni dobri rezultati (rang 18), a pokrenut je i niz uspješnih implementacija javnih politika usmjerenih rješavanju problema manjka digitalnih vještina poput e-škole, stipendija za STEM područja i dr. Valja također istaknuti da domaći poslovni sektor ostvaruje spor ali pozitivan napredak u usvajanju digitalne tehnologije (rang 21) no i dalje ponešto zaostaje za EU prosjekom. Ovakav trend odražava činjenicu da je u proces digitalizacije  poslovnog sektora uključen velik broj institucija, od akademske zajednice do poslovnog sektora, industrije i institucija središnje vlasti. 

Najslabije DESI komponente se odnose na domaću digitalnu infrastrukturu (rang 27) i implementaciju digitalizacije u javnom sektoru (rang 25). Slabo razvijena digitalna infrastruktura se uvelike može povezati sa tržišnom dominacijom Hrvatskog Telekoma što podržava postojeće stanje na tržištu i slabi inicijative manjih operatera za (skupim) ulaganjima u digitalnu infrastrukturu. Dodatno, tržišna dominacija HTa umanjuje potencijal za povlačenje EU sredstava za investicije u širokopojasne mreže i infrastrukturu koja podržava brzi internet. Nacionalne ekonomske i razvojne politike digitalne ekonomije bi trebalo stoga usmjeriti u defragmentaciju  telekom tržitšta. Digitalizacija u javnom sektoru ima pozitivan ali spor trend, dok sveukupna DESI pozicija ove komponente značajno zaostaje u odnosu na europski prosjek. Pozitivno je što postoji niz digitalizacijiskih inicijativa u javnom sektoru poput e-građani, e-uprava, e-računi, elektronička osobna iskaznica, uspostava Zajedničkog centra za usluge u oblaku i mnoštvo usluga e-zdravstva.

Iako zaostaje u odnosu na europski prosjek, Hrvatska je među uspješnijim zemljama zapadnog Balkana prema nizu pokazatelja digitalne ekonomije koje pak zbog svog perifernog položaja u odnosu na EU povijesno zaostaju u većini razvojnih pokazatelja pa tako i u intenzitetu i opsegu digitalne transformacije: korištenje širokopojasne mreže, udjela digitalnog sektora u gospodarstvu, javnim digitalnim uslugama i dr. Digitalno zaostajanje je dominantno povezano sa deficitima u regulatornom okviru, političkoj klimi i poslovnim uvjetima, a cijena nedovoljnog uključivanja ovih zemalja  u proces digitalne transformacije je njihovo daljnje tehnološko i razvojno zaostajanje, gubitak radnih mjesta, odljev obrazovane radne snage i dr. Ipak, valja istaknuti da ovu skupinu zemalja karakterizira značajna heterogenost u stupnju digitalne transformacije pri čemu relativno najviše pozicije zauzimaju Slovenija i Hrvatska dok su Albanija i Kosovo na posljednjem mjestu. Na ovakve relativne pozicije ponešto utječe i kriterij koji se promatra: [Network Readiness Indeks](http://reports.weforum.org/global-information-technology-report-2016/networked-readiness-index/) (globalni indeks koji uključuje 139 zemalja i objavljuje ga World Economic Forum) ili DESI indeks. [Studija](https://www.eizg.hr/userdocsimages//vijesti/vijesti_dogadaji/dt_studija/wb6-study.pdf) ističe kako se Hrvatska nalazi u na granici 30-40 % raspona distribucije intenziteta digitaliziranosti u globalnom uzorku zemalja. Rezultati  impliciraju kako povećanje intenziteta digitaliziranosti u Hrvatskoj (skupini zapadno-balkanskih zemalja)  ima znatno veći efekt na čimbenike ekonomskog rasta i društvenog razvoja nego u globalnom uzorku. Osim što takav rezultat upućuje na veličinu domaćeg „digitalnog jaza“ u odnosu na svjetsku tehnološku granicu, on je ujedno i snažan indikator potencijala (javnih) politika koje podupiru digitalizacijske procese.

Pošto ne postoji jedinstven konsenzus oko definicije niti kvantifikacije digitalne ekonomije, veličina hrvatske digitalne ekonomije se u duhu dobre prakse OECD-a može procijeniti kao agregat tvrtki iz sektora informacija i komunikacija (J58:J63) i tehnoloških tvrtki iz prerađivačkog sektora (C262:C264). Na temelju tako određene mjere, digitalni sektor u Hrvatskoj čini oko 6,5 tis tvrtki i zaposljava približno 48 tis ljudi u 2017 godini. Broj novih tvrtki iz digitalne ekonomije je u zadnjih 15 godina povećan više od  100%, a broj zaposlenih je porastao za oko 10 tisuća ljudi i prerastao razinu prije izbijanja ekonomske krize iz 2007 godine. Zanimljivo je primjetiti da je najdinamičniji porast zapošljavanja primjetan nakon 2014 godine, paralelno sa europskim politikama digititalizacije i unaprijeđenja jedinstvenog digitalnog tržišta ali i užurbanim nastojanjima Hrvatske da se uključi u treći val digitalne transformacije. Prosječne plaće u hrvatskoj digitalnoj ekonomiji zadnjih nekoliko godina su na razini oko 12 tis kn i znatno su iznad državnog prosijeka te među najvišima u industrijskim sektorima, a najisplativije je raditi u mikro ili velikim pouzećima dok mala i srednja poduzeća u prosjeku plaćaju manje za rad.

Poslovanje tvrtki iz digitalne ekonomije je u 2017 godini bilo na razini 40,2 mlrd kn prihoda i dobiti od 3,7 mlrd kn. Od toga je 7,4 mlrd ostvareno iz poslovanja u inozemstvu pri čemu je udio izvoza digitalne ekonomije u ukupnom izvozu hrvatskih poduzeća u blagom padu još od predkriznih godina, uz poneku pozitivnu godinu. Profitabilnost sektora pokazuje znatno veći udio dobiti digitalne eknomije, na razini od 13 %, u ukupnoj dobiti hrvatskih poduzeća od udjela prihoda u ukupnim prihodima.  Zanimljivo je da unatoč dobrom poslovanju, digitalna ekonomija već skoro čitavo desetljeće ne povećava stabilni udio od oko 6 % prihoda u ukupnim prihodima svih poduzeća u Hrvatskoj. Štoviše, taj je udio u posljednje tri godine u laganom padu. Ukupna stvorena dodana vrijednost tvrtki iz digitalne ekonomije nešto je viša od 15,8 mlrd kn. Udio digitalnog sektora time je na razini nešto nižoj od 10 % ukupne dodane vrijednosti privatnog sektora uz trend pada tog udjela u zadnje 4 godine. Smanjenje doprinosa digitalne ekonomije ukupnoj dodanoj vrijednosti u padu je od 2005 godine kada je udio dodane vrijednosti bio viši od 13 % ukupne dodane vrijednosti.

Digitalna ekonomija pridonosi povećanju tehnoloških kapaciteta gospodarstva na razini ulaganja u istraživanje i razvoj 2017 godine od skoro 200 mil kn što je  više od 50 mil kn nego u 2016 godini i skoro 20% ukupnih ulaganja u hrvatskih poduzeća u istraživanje i razvoj. Drugi pojačani investicijski ciklus sektora u zadnjih 10 godina je primjetan i u postupnom povećanju udjela tehnoloških investicija digitalne ekonomije u ukupnim izdatcima hrvatskih poduzeća za istraživanje i razvoj koji je 2014 godine iznosio tek 5%. To je ohrabrujući rezultat u kotekstu visoko procijenjenih multiplikativnih efektata tehnoloških investicija digitalne ekonomije na opću produktivnost gospodarstva uloge u smanjenju tehnološkog i razvojnog jaza hrvatskog gospodarstva i EU.

Zaključno, digitalna ekonomija predstavlja ekonomski sektor koji posluje na globalnoj tehnološkoj granici i kao takav je bitan faktor transfera tehnologije te povećanja produktivnosti  gospodarstva. Nositelji politika su prepoznali transformativnu ulogu digitalne ekonomije i usmjerili pažnju na poticanje njenog razvoja. Hrvatska se u tim trendovima nalazi na granici između 30- 40 % globalnog digitalizacijskog intenziteta, a u europskom kontekstu, u zadnjoj četvrtini. Ipak, uz Sloveniju, Hrvatska je u vrhu regionalno usporedivih balkanskih zemalja. Najveće prepreke domaćem razvoju su manjak infrastrukture i nedovoljna implementacija digitalnih platformi u javnom sektoru. Sa druge strane, potencijalne poluge za razvoj su stanovništvo koje je otvoreno prema digitalnim trendovima i dobro obrazovani domaći IT stručnjaci. Pokazatelji poslovanja tvrtki iz hrvatske digitalne ekonomije upućuju na njihovu dobru profitabilnost i tehnološki doprinos ali ujedno i stagnaciju i/ili opadanje u odnosu na ukupno poslovanje hrvatskih firmi.
